# Project information
site_name: 'Deep Learning Wizard'
site_description: 'We deploy a top-down approach that enables you to grasp deep learning theories and code easily and quickly. Used by thousands of students and professionals from top tech companies, research institutions.'
site_author: 'Ritchie Ng'
site_url: 'https://www.deeplearningwizard.com/'

# Navigation
pages:
    - Home: index.md
    - Supporters: supporters.md
    - Reviews: review.md
    - Deep Learning Tutorials:
      - Introduction: deep_learning/intro.md
      - Course Progression: deep_learning/course_progression.md
      - Matrices: deep_learning/practical_pytorch/pytorch_matrices.md
      - Gradients: deep_learning/practical_pytorch/pytorch_gradients.md
      - Linear Regression: deep_learning/practical_pytorch/pytorch_linear_regression.md
      - Logistic Regression: deep_learning/practical_pytorch/pytorch_logistic_regression.md
      - Feedforward Neural Networks: deep_learning/practical_pytorch/pytorch_feedforward_neuralnetwork.md
      - Convolutional Neural Networks: deep_learning/practical_pytorch/pytorch_convolutional_neuralnetwork.md
      - Recurrent Neural Networks: deep_learning/practical_pytorch/pytorch_recurrent_neuralnetwork.md
      - Long Short Term Memory Neural Networks: deep_learning/practical_pytorch/pytorch_lstm_neuralnetwork.md
      - Derivative, Gradient and Jacobian: deep_learning/boosting_models_pytorch/derivative_gradient_jacobian.md
      - Forward- and Backward-propagation and Gradient Descent: deep_learning/boosting_models_pytorch/forwardpropagation_backpropagation_gradientdescent.md
      - Learning Rate Scheduling: deep_learning/boosting_models_pytorch/lr_scheduling.md
      - Optimization Algorithms: deep_learning/boosting_models_pytorch/optimizers.md
      - Weight Initialization and Activation Functions: deep_learning/boosting_models_pytorch/weight_initialization_activation_functions.md
      - Supervised Learning to Reinforcement Learning: deep_learning/deep_reinforcement_learning_pytorch/supervised_to_rl.md
      - Markov Decision Processes and Bellman Equations: deep_learning/deep_reinforcement_learning_pytorch/bellman_mdp.md
      - Additional Readings: deep_learning/readings.md

    - Scalable Database Tutorials:
      - Welcome: database/intro.md
      - Cassandra Cluster Setup: database/setting_up_cluster.md

    - News:
      - Welcome: news/news.md
      - AMMI (AIMS) supported by Facebook and Google, November 2018: news/ammi_facebook_google_recap_2018_11_21.md
      - NExT++ AI in Healthcare and Finance, Nanjing, November 2018: news/nanjing_next_nus_tsinghua_ai_finance_healthcare_2018_11_01.md
      - Recap of Facebook PyTorch Developer Conference, San Francisco, September 2018: news/facebook_pytorch_devcon_recap_2018_10_02.md
      - Facebook PyTorch Developer Conference, San Francisco, September 2018: news/facebook_pytorch_developer_conference_2018_09_05.md
      - NUS-MIT-NUHS NVIDIA Image Recognition Workshop, Singapore, July 2018: news/nvidia_nus_mit_datathon_2018_07_05.md
      - Featured on PyTorch Website 2018: news/deep_learning_wizard_1y_2018_06_01.md
      - NVIDIA Self Driving Cars & Healthcare Talk, Singapore, June 2017: news/nvidia_self_driving_cars_talk_2017_06_21.md
      - NVIDIA Inception Partner Status, Singapore, May 2017: news/deep_learning_wizard_nvidia_inception_2018_05_01.md

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  feature:
    tabs: true
  logo:
    icon: 'whatshot'
  palette:
    primary: 'blue-grey'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: './assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Equations
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Social
extra:
  social:
    - type: 'github'
      link: 'https://github.com/ritchieng'
    - type: 'facebook'
      link: 'https://www.facebook.com/DeepLearningWizard/'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/deeplearningwizard/'
  disqus: 'deep-learning-wizard'


# Google Analytics
google_analytics:
  - 'UA-122083328-1'
  - 'auto'

# Copyright
copyright: 'Copyright &copy; 2018 Deep Learning Wizard'
